---
- name: Set up SSH config for pis
  hosts: original
  become: yes

  tasks:
    - name: Update sshd config
      copy:
        src: ./file/sshd_config
        dest: /etc/ssh/sshd_config
      notify:
        - restart sshd

  handlers:
    - name: restart sshd
      command: systemctl reload sshd


