---
- name: For debugging, test, etc fact finding
  connection: local
  gather_facts: no
  hosts: localhost

#   vars_files:
#   - fake-api-key.yaml

  tasks:
    - name: Register output of 'uptime' command
      command: uptime
      register: system_uptime

    - name: Print a message if a command resulted in a change
      debug:
        msg: "Command resulted in a change"
      when: system_uptime is changed
