---
- hosts: k8pis
  become: true
  vars_files:
   - ./vars/user_vars.yaml
  
  tasks:
  - name: Setup SSH config
    include_tasks: ./ssh/playbook.yaml

  - name: Setup networking configuration
    include_tasks: ./networking/playbook.yaml

  - name: Setup cgroups limit
    includes_tasks: ./cgroups/playbook.yaml
  
  handlers:
    - name: restart sshd
      command: systemctl reload sshd
    
    - name: update hostname
      command: "hostname {{ pi_hostname }}"

    - name: delete dhcp leases
      file:
        path: /var/lib/dhcp/dhclient.leases
        state: absent
      with_items:
        - /var/lib/dhcp/dhclient.leases
        - /var/lib/dhcpcd5/dhcpcd-eth0.lease