---
- name: Check if cgroups limit has been enabled
  shell: cat /boot/firmware/cmdline.txt
  register: check_cgroups_enabled_result

- name: Enable cgroups limit if not enabled already
  shell: sed -i '$ s/$/ cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1/' /boot/firmware/cmdline.txt
  when: check_cgroups_enabled_result.stdout.find('cgroup_enable=cpuset') == -1
    
  