---
- name: Set the current MAC address for eth0.
  set_fact:
    pi_mac_address: "{{ ansible_facts.default_ipv4.macaddress }}"

- name: Ensure dhcpcd is installed
  apt:
    name: dhcpcd5
    state: present

- name: Ensure dhcpcd service is running
  service:
    name: dhcpcd
    state: started
    enabled: true

- name: Set variables based on eth0 MAC address.
  set_fact:
    pi_hostname: "{{ mac_address_mapping[pi_mac_address].name }}"
    pi_ip_address: "{{ mac_address_mapping[pi_mac_address].ip }}"

- name: Set up networking-related files.
  template:
    src: "templates/{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { template: hostname.j2, dest: /etc/hostname }
    - { template: hosts.j2, dest: /etc/hosts }
    - { template: resolv.conf.j2, dest: /etc/resolv.conf }
    - { template: dhcpcd.conf.j2, dest: /etc/dhcpcd.conf }
  notify:
    - update hostname
    - delete dhcp leases